#!/bin/sh
# Minimal Gradle wrapper launcher.
# The binary gradle/wrapper/gradle-wrapper.jar is generated by "gradle wrapper" (see README.md).

APP_HOME=$(cd "$(dirname "$0")" && pwd -P)
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
    echo "gradle-wrapper.jar fehlt." >&2
    echo "Einmalig ausfuehren (benoetigt installiertes Gradle 9.4+):  gradle wrapper --gradle-version 9.4.1" >&2
    echo "Oder einfach GitHub Actions benutzen (siehe README.md), dort ist kein Wrapper noetig." >&2
    exit 1
fi

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi

exec "$JAVACMD" -Xmx64m -Xms64m -classpath "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
